# Generated by Django 4.0.4 on 2022-05-07 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, verbose_name='Biografía')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, verbose_name='Web')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/pictures', verbose_name='avatar')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='nombre usuario')),
            ],
        ),
    ]
